### ISSUE TITLE
JWT/Guest Token Support

### ISSUE THREAD

**Issue by bmeade90** [webex/widgets#21]
The Browser SDK (https://github.com/webex/webex-js-sdk) and Space/Recents Widgets (https://github.com/webex/react-widgets) currently support passing a guest token/JWT for authentication directly via guestToken.

Currently the Webex Meetings widget only supports passing an Access Token for authentication.  This requires extra server-side code for customers with guest access use cases as they now need to exchange the JWT for an access token.

Ideally the Webex Meetings widget would be updated to support JWT's natively.

**Comment by olivierproffit** [comment]
Hi @bmeade90 thanks for this feature request and your interest in Webex Widgets. As Product Manager, I love hearing your needs. Your request makes total sense. In order to make it more visible, votable by others, and even higher in our backlog, could you post it in our feature request tool with most details possible (expected user flow, use case, business case, ...): https://ciscocollaboration.aha.io/session/new
Thanks

**Comment by lalli-flores** [comment]
@bmeade90, if you use JWT during development, I've created a small script that can give you an access token from a JWT token: https://github.com/lalli-flores/webex.guest.generator
