### ISSUE TITLE
UMD Bundle

### ISSUE THREAD

**Issue by bmeade90** [webex/widgets#22]
Many customers are wanting to quickly embed Webex Meetings into their webpages and may not have a React or NPM environment today.

The Space/Recents widget (https://github.com/webex/react-widgets) has a pre-compiled bundle that customers can use that allows those customers to very quickly deploy Webex widgets.  Ideally this is something that could be done for this Webex Meetings widget as well.

More info on the Cisco-hosted production bundle for the Space/Recents widgets:
https://github.com/webex/react-widgets/tree/master/packages/node_modules/@webex/widget-space
```
CDN
Using our CDN requires the least amount of work to get started. Add the following into your HTML file:

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://code.s4d.io/widget-space/production/main.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://code.s4d.io/widget-space/production/bundle.js"></script>

For the latest builds that are pulled from the head of the master branch:

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://code.s4d.io/widget-space/latest/main.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://code.s4d.io/widget-space/latest/bundle.js"></script>

**Comment by olivierproffit** [comment]
Hi @bmeade90  thanks for this feature request and your interest in Webex Widgets. As Product Manager, I love hearing your needs. Your request makes total sense. In order to make it more visible, votable by others, and even higher in our backlog, could you post it in our feature request tool with most details possible (expected user flow, use case, business case, ...): https://ciscocollaboration.aha.io/session/new
Thanks
